before_script: npm install
script: npm run deploy
language: node_js
node_js:
- '6'
branches:
  only:
  - deploy
env:
  global:
  - GH_REF: github.com/uvicwebdev/HackUVic.git
  - secure: XoRG/iqgrVmICvDJJhs6SCSv5NYSGUoswX2FNXHddklqBDhViGL3A/jYlPLqAo/o9+PPK1RkP+Yf8NgBZTG0CacESPNm7a6L64Ddd1rilQyQ3IhSX+ydeKhXs3beDh7+NQ1dbeEauaDpS8oWkbqgoHG/rPsOAcmrY6qugwduoNEUZx0lWJw4leRtY3BobdvfUVpkitnWRSZUOMfP85Yea5LBe7KCPzVjm21KcghuJy7UVPhcknX7WKhi5avx9j4OsaZBMLPcCzPYK4ZzeOtsB58hLxtW0x4z/M6P7vgZmFFbhur6m923VG3prfvx0Hz+cdfIjvXKJxDKbAqDmdAAS4mrN6eQbF0x7X/dB57mDujzgPJJDDadAo0kJRZ1VuyAneUaZVyuZe2oOgbdpU/9/ECJRu3L7SYz6txN1dz1kEcxS8HPokXXP2PonaBXMkCkPAM+aNu/flVvFf/3GzW6cPkVL14HfCzF9QMLeyGsnUgLXW8rgZe5Y2AVPY+G/Snsts3QFl/+TJTKT6bq8RoRoBUkHoshRzskK9ejNElxiODsFZzfxiAw1KaH2Yy39XzCznd197uqhvTEBEh/ELOhKLqLdW6KsVT5BMyPRev++iRLflUUn1um0JYiMcUeclLWZdZoyYY8qpvYX+1ElsdESbkKEdQqHCaC2RFPHDpSTmw=
