before_script: npm install
script: npm run deploy
language: node_js
node_js:
  - "6"
branches:
  only:
  - deploy
env:
  global:
  - GH_REF: github.com/hwkr/hwkr.github.io.git
  - secure: kCa5ckgKICYuqx/QrJO9FqjW/hD6/1C0oV2AUbyj5gGqLDJU04xdNfMSPDNBvSEUWC3YJ1CYfAi9hMfHOHsprRcxi9qU3oUE44jKCNkeAyCQi1wboTuCCdAFEF+iSegsszheaoPB92AP9PBC4EU/dXm1iYmxcCL/Ic76yPQQDxTLZeDRDGVGH4NzzLPLXmItBgcRnFWSoLkuEE8riw5/IsYZbfs4hS/3qgVJRgMpW3z6nnfnY61XFifUTFtFBAs4TzbnGLi7guiYP7W+9xl89bCRR2JGNws7kmuxP2+M8iC0t6SudFyr69svwh/oGDho023/sXSl8x56FTZlmmcIzGo74EIUCxGzQHwK8jzUai2TfykNxLCDrdCMBaVsFvD6xgVdgiHMxxzu06LTTsOuuip3TiGq6TKobYTZ8Oc4HKU+ZTN/3DHbXJ3nnqg+v3csbuSaRkk/g64tmhO4TnSboNg+2MnO5itQ78Zr5+kNMgaSwva5NoRX+riQXYZLa/S+Aurs9Ze1e4Bky0WWbIxfcjouO3TaoX8Aa9rX/yhJs/EOxsaPuxiHyjnVJZGK/KmfgVwzt/uc04p5lCicIu34dzGsIZjqn/1gy8Hn5A8k4S9jgfcGpio2NTKt/iHfD7ewJbY4OZZo+h8F3p98fDGuyANL4SspSWMbnASEQSZ+clA=
